# desktop profile - targets Ubuntu Desktop and flavors.

remove_lxd=true
remove_snapd=false
disable_telemetry=true
remove_cloudinit=true
remove_avahi=false
remove_pro_client=false
pin_removed=false
clean_motd=true
harden_firewall=true
harden_ssh=true
harden_kernel=true
encrypt_dns=false
enable_unattended_upgrades=true
install_fail2ban=false
tune_performance=true
cap_journald=true
extra_packages=
